In [6]:
import torch

In [9]:
def alzebra(a,b):
    return torch.randn(a,b)

def aljebra(a,b):
    return torch.randn(b,a)
    
eval("alzebra(2,3)@aljebra(2,3)")

tensor([[ 0.5500, -2.9076],
        [-0.4125,  0.5840]])

In [10]:
alzebra(2,3)@aljebra(2,3)

tensor([[ 1.3971, -0.3087],
        [-0.3146,  0.1134]])

In [25]:
counter = 0
import pandas as pd

df = pd.DataFrame([[2,3],[4,5]])
df.rename(columns = {0:'Column1',1:'Column2'})
counter = counter+df.iloc[1][1]
print(counter)

5


Column1  Column2
0        2        3
1        4        5

In [27]:
pip install -q ipython

Note: you may need to restart the kernel to use updated packages.


In [5]:
from IPython import get_ipython
ipython = get_ipython()
result = ipython.run_cell("""
counter = 7
import pandas as pd
import torch

df = pd.DataFrame([[2,3],[4,5]])
df.rename(columns = {0:'Column1',1:'Column2'})
counter = counter+df.iloc[1][1]
print(counter)
torch.randn(counter)
""")

12


tensor([-1.9123,  0.1678,  0.6882, -0.0486,  0.1731, -0.0801, -0.9577, -0.0945,
        -1.2874,  0.4390,  0.2123,  0.3966])

In [6]:
counter = 7
import pandas as pd
import torch

df = pd.DataFrame([[2,3],[4,5]])
df.rename(columns = {0:'Column1',1:'Column2'})
counter = counter+df.iloc[1][1]
print(counter)
torch.randn(counter)

12


tensor([ 0.2577,  0.1263,  1.5199, -1.5585, -1.4927, -1.3101,  1.3938,  1.3056,
         0.0892, -0.4559, -0.9276, -2.8242])

In [1]:
from IPython.core.interactiveshell import InteractiveShell
ipython = InteractiveShell()
result = ipython.run_cell("""
counter = 7
import pandas as pd
import torch

df = pd.DataFrame([[2,3],[4,5]])
df.rename(columns = {0:'Column1',1:'Column2'})
counter = counter+df.iloc[1][1]
print(counter)
torch.randn(counter)
""")

12
Out[1]: 
tensor([ 2.3743, -0.6894, -0.1947, -0.8825, -0.8387,  0.2825, -1.1453, -0.8488,
         0.0390, -0.4142,  1.6118, -0.0242])


In [3]:
eval('2+3')

5

In [8]:
namespace={}
result = exec('2+3',namespace)
print(result)

None
